stages:
  prepare:
    cmd: python src/prepare.py data/raw/Inpatient.pkl data/raw/Outpatient.pkl
    deps: 
      - data/raw/Inpatient.pkl
      - data/raw/Outpatient.pkl
      - src/prepare.py
    params:
    - prepare.test_ratio
    - prepare.random_seed
    outs:
    - data/prepared
